### ISSUE TITLE
Invalid multiplications?

### ISSUE THREAD

**Issue by jeremysanders** [dbartilson/fh_table#2]
I think your hash functions rely on multiplication by large numbers wrapping around. From what I can see, this behaviour is not allowed in the Fortran specifications. See https://gcc.gnu.org/onlinedocs/gfortran/Behavior-on-integer-overflow.html#:~:text=The%20behavior%20of%20gfortran%20on,detect%20such%20code%20at%20runtime

At least, probably `-fwrapv` should be used for gfortran. For standards compliance, probably you'd need to break up the multiplication operands into high and low 32 bit parts, and work out the 64 bit multiplication using bit shifts, like a 32 bit processor would.

**Comment by dbartilson** [comment]
@jeremysanders If you feel like it, please check through my changes on this branch. Otherwise I will just merge it soon.
